### ISSUE TITLE
Remapping Keyboard Issues

### ISSUE THREAD

**Issue by PlayPretendexp** [komefai/PS4Macro.Remote#1]
Found 2 issues with the PS4MacroRemote (Remapping Feature). You absolutely cannot press 2 or more keys at the same time using the keyboard. For example X and O together (Esc and Enter) Or Up and Forward for a Jump Forward motion... Or Down and Back for a crouching block.

Second issue is.... if I hold forward to walk forward it would randomly stop holding the key for a split second and input another forward while still holding down the key nonstop. It happens with any key on the keyboard not just forward. Best way to explain the last issue is with the Options button (on the keyboard). if i hold it down it would literally pause and resume the game nonstop. Again the problems is with the keyboard not the controller itself.﻿ This is especially an issue with the directional keys because my character would walk forward or backward with like a stutter pause and continue.

**Comment by komefai** [comment]
This problem has been fixed in [v1.1](https://github.com/komefai/PS4Macro.Remote/releases/tag/v1.1.0)
